-- TimescaleDB initialization script.
-- Скрипты из /docker-entrypoint-initdb.d/ выполняются автоматически
-- при ПЕРВОМ запуске контейнера (когда volume с данными пуст).
--
-- Здесь мы:
--   1. включаем расширение TimescaleDB;
--   2. создаём таблицу flight_prices (та же схема, что в ORM-модели);
--   3. превращаем её в гипертаблицу с чанками по 1 дню (time buckets);
--   4. включаем колоночное сжатие чанков и политику автосжатия;
--   5. (опционально) включаем политику хранения данных.
--
-- Приложение вызывает SQLAlchemy create_all(checkfirst=True), которое
-- увидит уже существующую таблицу и НЕ будет её пересоздавать.

CREATE EXTENSION IF NOT EXISTS timescaledb;

CREATE TABLE IF NOT EXISTS flight_prices (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    origin         VARCHAR(100) NOT NULL,
    destination    VARCHAR(100) NOT NULL,
    departure_date DATE         NOT NULL,
    airline        VARCHAR(200),
    flight_number  VARCHAR(50),
    departure_time VARCHAR(20),
    arrival_time   VARCHAR(20),
    duration       VARCHAR(50),
    price          DOUBLE PRECISION NOT NULL,
    currency       VARCHAR(10) DEFAULT 'RUB',
    stops          INTEGER     DEFAULT 0,
    scraped_at     TIMESTAMP   NOT NULL DEFAULT now(),
    -- scraped_at обязан быть в PK — это колонка партиционирования гипертаблицы
    PRIMARY KEY (id, scraped_at)
);

CREATE INDEX IF NOT EXISTS ix_flight_prices_origin         ON flight_prices (origin);
CREATE INDEX IF NOT EXISTS ix_flight_prices_destination    ON flight_prices (destination);
CREATE INDEX IF NOT EXISTS ix_flight_prices_departure_date ON flight_prices (departure_date);
CREATE INDEX IF NOT EXISTS ix_flight_prices_scraped_at     ON flight_prices (scraped_at);

-- Превращаем таблицу в гипертаблицу. chunk_time_interval = размер "time bucket"
-- по которому TimescaleDB режет данные на чанки. 1 день — разумно для частого
-- сбора цен; меняйте под вашу нагрузку (например INTERVAL '1 hour' или '7 days').
SELECT create_hypertable(
    'flight_prices',
    'scraped_at',
    chunk_time_interval => INTERVAL '1 day',
    if_not_exists       => TRUE
);

-- Включаем колоночное сжатие чанков.
-- segmentby — по каким колонкам группировать строки внутри сжатого чанка
-- (запросы по маршруту origin/destination будут эффективны);
-- orderby — порядок строк внутри сегмента (свежие сверху).
ALTER TABLE flight_prices SET (
    timescaledb.compress,
    timescaledb.compress_segmentby = 'origin, destination',
    timescaledb.compress_orderby   = 'scraped_at DESC'
);

-- Политика автосжатия: чанки старше 7 дней сжимаются автоматически фоновым воркером.
SELECT add_compression_policy('flight_prices', INTERVAL '7 days');

-- (Опционально) автоудаление данных старше 1 года. Раскомментируйте при необходимости.
-- SELECT add_retention_policy('flight_prices', INTERVAL '365 days');
